  execution:
    user: 1000:1000
    container_name: execution
    image: ethereum/client-go:stable
    restart: always
    stop_grace_period: 1m
    command: |
# incorrect flag          --network=$ETH_NETWORK 
      --http
      --http.addr=0.0.0.0
      --http.port=$ETH_NODE_RPC_PORT
      --http.api=eth,net,web3
      --http.vhosts=*
      --allow-insecure-unlock
      --ws
      --ws.addr=0.0.0.0
      --ws.port=8546
      --ws.api=eth,net,web3
    env_file:
      - $HOME/.bash_profile
    ports:
      - "$EL_P2P_PORT:$EL_P2P_PORT/tcp" # p2p
      - "$EL_P2P_PORT:$EL_P2P_PORT/udp" # p2p
#      - "127.0.0.1:$ETH_NODE_RPC_PORT:$ETH_NODE_RPC_PORT" # http RPC port
#      - "127.0.0.1:8546:8546" # websocket port
#      - "127.0.0.1:8551:8551" # engine RPC port
    expose:
      - $ETH_NODE_RPC_PORT
      - 8546
      - 8551 
    volumes:
      - $ETH_HOMEDIR/eth-node/jwtsecret:/jwtsecret
      - $ETH_HOMEDIR/eth-node/el-client:/root/.ethereum
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "local"
    networks:
      net:
