  execution:
    user: 1000:1000
    container_name: execution 
    image: nethermind/nethermind:latest
    restart: always
    stop_grace_period: 1m
    command: |
      --config=$ETH_NETWORK
      --datadir=/data
      --log=INFO
      --Sync.SnapSync=false
      --JsonRpc.Enabled=true
      --JsonRpc.Host=0.0.0.0
      --JsonRpc.Port=$ETH_NODE_RPC_PORT
      --JsonRpc.EnabledModules=[Web3,Eth,Subscribe,Net,]
      --JsonRpc.JwtSecretFile=/jwtsecret/jwtsecret.hex
      --JsonRpc.EngineHost=0.0.0.0
      --JsonRpc.EnginePort=8551
      --Network.DiscoveryPort=$EL_P2P_PORT
      --Network.P2PPort=$EL_P2P_PORT
      --Pruning.CacheMb=2048
      --HealthChecks.Enabled=false
    env_file:
      - $HOME/.bash_profile
    ports:
      - "$EL_P2P_PORT:$EL_P2P_PORT/tcp" # p2p
      - "$EL_P2P_PORT:$EL_P2P_PORT/udp" # p2p
#      - "127.0.0.1:$ETH_NODE_RPC_PORT:$ETH_NODE_RPC_PORT" # http RPC port
#      - "127.0.0.1:8546:8546" # websocket port
#      - "127.0.0.1:8551:8551" # engine RPC port
    expose:
      - $ETH_NODE_RPC_PORT
      - 8546
      - 8551
    volumes:
      - $ETH_HOMEDIR/eth-node/jwtsecret:/jwtsecret
      - $ETH_HOMEDIR/eth-node/el-client:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "local"
    networks:
      net:
