  consensus:
    user: 1000:1000
    container_name: consensus 
    image: statusim/nimbus-eth2:amd64-latest
    restart: always
    stop_grace_period: 30s
    command: |
      --network=$ETH_NETWORK
      --data-dir=/data/beacon
      --web3-url=http://execution:8551
      --log-level=info
      --non-interactive
      --rest
      --rest-address=0.0.0.0
      --rest-port=5052
      --rest-allow-origin=*
      --doppelganger-detection
      --max-peers=80
      --enr-auto-update
      --jwt-secret=/jwtsecret/jwtsecret.hex
      --suggested-fee-recipient=$FEE_RECIPIENT
      --tcp-port=13000
      --udp-port=12000
    ports:
      - "12001:12000/udp" # p2p
      - "13001:13000" # p2p
#      - "127.0.0.1:5052:5052" # rest api
    volumes:
      - $HOMEDIR/eth-node/cl-client:/data
      - $HOMEDIR/eth-node/jwtsecret:/jwtsecret
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    logging:
      driver: "local"
    networks:
      net:
